// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FpDbEvent.proto

package com.kloudfuse.log4j2.model.proto;

public final class FpDbEventOuterClass {
  private FpDbEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FpDbEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.FpDbEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fingerprintHash = 1;</code>
     */
    java.lang.String getFingerprintHash();
    /**
     * <code>string fingerprintHash = 1;</code>
     */
    com.google.protobuf.ByteString
        getFingerprintHashBytes();

    /**
     * <code>string fingerprintStr = 2;</code>
     */
    java.lang.String getFingerprintStr();
    /**
     * <code>string fingerprintStr = 2;</code>
     */
    com.google.protobuf.ByteString
        getFingerprintStrBytes();

    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */
    int getParamIndicesByNameCount();
    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */
    boolean containsParamIndicesByName(
        java.lang.String key);
    /**
     * Use {@link #getParamIndicesByNameMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getParamIndicesByName();
    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getParamIndicesByNameMap();
    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */

    int getParamIndicesByNameOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */

    int getParamIndicesByNameOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */
    int getParamTypesByNameCount();
    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */
    boolean containsParamTypesByName(
        java.lang.String key);
    /**
     * Use {@link #getParamTypesByNameMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getParamTypesByName();
    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getParamTypesByNameMap();
    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */

    java.lang.String getParamTypesByNameOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */

    java.lang.String getParamTypesByNameOrThrow(
        java.lang.String key);

    /**
     * <code>string partitionKey = 5;</code>
     */
    java.lang.String getPartitionKey();
    /**
     * <code>string partitionKey = 5;</code>
     */
    com.google.protobuf.ByteString
        getPartitionKeyBytes();
  }
  /**
   * Protobuf type {@code model.FpDbEvent}
   */
  public  static final class FpDbEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.FpDbEvent)
      FpDbEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FpDbEvent.newBuilder() to construct.
    private FpDbEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FpDbEvent() {
      fingerprintHash_ = "";
      fingerprintStr_ = "";
      partitionKey_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FpDbEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fingerprintHash_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fingerprintStr_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                paramIndicesByName_ = com.google.protobuf.MapField.newMapField(
                    ParamIndicesByNameDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              paramIndicesByName__ = input.readMessage(
                  ParamIndicesByNameDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              paramIndicesByName_.getMutableMap().put(
                  paramIndicesByName__.getKey(), paramIndicesByName__.getValue());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                paramTypesByName_ = com.google.protobuf.MapField.newMapField(
                    ParamTypesByNameDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              paramTypesByName__ = input.readMessage(
                  ParamTypesByNameDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              paramTypesByName_.getMutableMap().put(
                  paramTypesByName__.getKey(), paramTypesByName__.getValue());
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              partitionKey_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.internal_static_model_FpDbEvent_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetParamIndicesByName();
        case 4:
          return internalGetParamTypesByName();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.internal_static_model_FpDbEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent.class, com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent.Builder.class);
    }

    private int bitField0_;
    public static final int FINGERPRINTHASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object fingerprintHash_;
    /**
     * <code>string fingerprintHash = 1;</code>
     */
    public java.lang.String getFingerprintHash() {
      java.lang.Object ref = fingerprintHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fingerprintHash_ = s;
        return s;
      }
    }
    /**
     * <code>string fingerprintHash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFingerprintHashBytes() {
      java.lang.Object ref = fingerprintHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fingerprintHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FINGERPRINTSTR_FIELD_NUMBER = 2;
    private volatile java.lang.Object fingerprintStr_;
    /**
     * <code>string fingerprintStr = 2;</code>
     */
    public java.lang.String getFingerprintStr() {
      java.lang.Object ref = fingerprintStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fingerprintStr_ = s;
        return s;
      }
    }
    /**
     * <code>string fingerprintStr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFingerprintStrBytes() {
      java.lang.Object ref = fingerprintStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fingerprintStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMINDICESBYNAME_FIELD_NUMBER = 3;
    private static final class ParamIndicesByNameDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.internal_static_model_FpDbEvent_ParamIndicesByNameEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> paramIndicesByName_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetParamIndicesByName() {
      if (paramIndicesByName_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamIndicesByNameDefaultEntryHolder.defaultEntry);
      }
      return paramIndicesByName_;
    }

    public int getParamIndicesByNameCount() {
      return internalGetParamIndicesByName().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */

    public boolean containsParamIndicesByName(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetParamIndicesByName().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamIndicesByNameMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getParamIndicesByName() {
      return getParamIndicesByNameMap();
    }
    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getParamIndicesByNameMap() {
      return internalGetParamIndicesByName().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */

    public int getParamIndicesByNameOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetParamIndicesByName().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
     */

    public int getParamIndicesByNameOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetParamIndicesByName().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PARAMTYPESBYNAME_FIELD_NUMBER = 4;
    private static final class ParamTypesByNameDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.internal_static_model_FpDbEvent_ParamTypesByNameEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> paramTypesByName_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetParamTypesByName() {
      if (paramTypesByName_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamTypesByNameDefaultEntryHolder.defaultEntry);
      }
      return paramTypesByName_;
    }

    public int getParamTypesByNameCount() {
      return internalGetParamTypesByName().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */

    public boolean containsParamTypesByName(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetParamTypesByName().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamTypesByNameMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getParamTypesByName() {
      return getParamTypesByNameMap();
    }
    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getParamTypesByNameMap() {
      return internalGetParamTypesByName().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */

    public java.lang.String getParamTypesByNameOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParamTypesByName().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
     */

    public java.lang.String getParamTypesByNameOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParamTypesByName().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PARTITIONKEY_FIELD_NUMBER = 5;
    private volatile java.lang.Object partitionKey_;
    /**
     * <code>string partitionKey = 5;</code>
     */
    public java.lang.String getPartitionKey() {
      java.lang.Object ref = partitionKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partitionKey_ = s;
        return s;
      }
    }
    /**
     * <code>string partitionKey = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPartitionKeyBytes() {
      java.lang.Object ref = partitionKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partitionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFingerprintHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fingerprintHash_);
      }
      if (!getFingerprintStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fingerprintStr_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetParamIndicesByName(),
          ParamIndicesByNameDefaultEntryHolder.defaultEntry,
          3);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetParamTypesByName(),
          ParamTypesByNameDefaultEntryHolder.defaultEntry,
          4);
      if (!getPartitionKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, partitionKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFingerprintHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fingerprintHash_);
      }
      if (!getFingerprintStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fingerprintStr_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetParamIndicesByName().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        paramIndicesByName__ = ParamIndicesByNameDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, paramIndicesByName__);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetParamTypesByName().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        paramTypesByName__ = ParamTypesByNameDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, paramTypesByName__);
      }
      if (!getPartitionKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, partitionKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent)) {
        return super.equals(obj);
      }
      com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent other = (com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent) obj;

      if (!getFingerprintHash()
          .equals(other.getFingerprintHash())) return false;
      if (!getFingerprintStr()
          .equals(other.getFingerprintStr())) return false;
      if (!internalGetParamIndicesByName().equals(
          other.internalGetParamIndicesByName())) return false;
      if (!internalGetParamTypesByName().equals(
          other.internalGetParamTypesByName())) return false;
      if (!getPartitionKey()
          .equals(other.getPartitionKey())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FINGERPRINTHASH_FIELD_NUMBER;
      hash = (53 * hash) + getFingerprintHash().hashCode();
      hash = (37 * hash) + FINGERPRINTSTR_FIELD_NUMBER;
      hash = (53 * hash) + getFingerprintStr().hashCode();
      if (!internalGetParamIndicesByName().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMINDICESBYNAME_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParamIndicesByName().hashCode();
      }
      if (!internalGetParamTypesByName().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMTYPESBYNAME_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParamTypesByName().hashCode();
      }
      hash = (37 * hash) + PARTITIONKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.FpDbEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.FpDbEvent)
        com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.internal_static_model_FpDbEvent_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetParamIndicesByName();
          case 4:
            return internalGetParamTypesByName();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableParamIndicesByName();
          case 4:
            return internalGetMutableParamTypesByName();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.internal_static_model_FpDbEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent.class, com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent.Builder.class);
      }

      // Construct using com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fingerprintHash_ = "";

        fingerprintStr_ = "";

        internalGetMutableParamIndicesByName().clear();
        internalGetMutableParamTypesByName().clear();
        partitionKey_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.internal_static_model_FpDbEvent_descriptor;
      }

      @java.lang.Override
      public com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent getDefaultInstanceForType() {
        return com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent build() {
        com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent buildPartial() {
        com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent result = new com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.fingerprintHash_ = fingerprintHash_;
        result.fingerprintStr_ = fingerprintStr_;
        result.paramIndicesByName_ = internalGetParamIndicesByName();
        result.paramIndicesByName_.makeImmutable();
        result.paramTypesByName_ = internalGetParamTypesByName();
        result.paramTypesByName_.makeImmutable();
        result.partitionKey_ = partitionKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent) {
          return mergeFrom((com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent other) {
        if (other == com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent.getDefaultInstance()) return this;
        if (!other.getFingerprintHash().isEmpty()) {
          fingerprintHash_ = other.fingerprintHash_;
          onChanged();
        }
        if (!other.getFingerprintStr().isEmpty()) {
          fingerprintStr_ = other.fingerprintStr_;
          onChanged();
        }
        internalGetMutableParamIndicesByName().mergeFrom(
            other.internalGetParamIndicesByName());
        internalGetMutableParamTypesByName().mergeFrom(
            other.internalGetParamTypesByName());
        if (!other.getPartitionKey().isEmpty()) {
          partitionKey_ = other.partitionKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fingerprintHash_ = "";
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public java.lang.String getFingerprintHash() {
        java.lang.Object ref = fingerprintHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fingerprintHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFingerprintHashBytes() {
        java.lang.Object ref = fingerprintHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fingerprintHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public Builder setFingerprintHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fingerprintHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public Builder clearFingerprintHash() {
        
        fingerprintHash_ = getDefaultInstance().getFingerprintHash();
        onChanged();
        return this;
      }
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public Builder setFingerprintHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fingerprintHash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fingerprintStr_ = "";
      /**
       * <code>string fingerprintStr = 2;</code>
       */
      public java.lang.String getFingerprintStr() {
        java.lang.Object ref = fingerprintStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fingerprintStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fingerprintStr = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFingerprintStrBytes() {
        java.lang.Object ref = fingerprintStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fingerprintStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fingerprintStr = 2;</code>
       */
      public Builder setFingerprintStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fingerprintStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fingerprintStr = 2;</code>
       */
      public Builder clearFingerprintStr() {
        
        fingerprintStr_ = getDefaultInstance().getFingerprintStr();
        onChanged();
        return this;
      }
      /**
       * <code>string fingerprintStr = 2;</code>
       */
      public Builder setFingerprintStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fingerprintStr_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> paramIndicesByName_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetParamIndicesByName() {
        if (paramIndicesByName_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParamIndicesByNameDefaultEntryHolder.defaultEntry);
        }
        return paramIndicesByName_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableParamIndicesByName() {
        onChanged();;
        if (paramIndicesByName_ == null) {
          paramIndicesByName_ = com.google.protobuf.MapField.newMapField(
              ParamIndicesByNameDefaultEntryHolder.defaultEntry);
        }
        if (!paramIndicesByName_.isMutable()) {
          paramIndicesByName_ = paramIndicesByName_.copy();
        }
        return paramIndicesByName_;
      }

      public int getParamIndicesByNameCount() {
        return internalGetParamIndicesByName().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
       */

      public boolean containsParamIndicesByName(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetParamIndicesByName().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParamIndicesByNameMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getParamIndicesByName() {
        return getParamIndicesByNameMap();
      }
      /**
       * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getParamIndicesByNameMap() {
        return internalGetParamIndicesByName().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
       */

      public int getParamIndicesByNameOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetParamIndicesByName().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
       */

      public int getParamIndicesByNameOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetParamIndicesByName().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParamIndicesByName() {
        internalGetMutableParamIndicesByName().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
       */

      public Builder removeParamIndicesByName(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParamIndicesByName().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableParamIndicesByName() {
        return internalGetMutableParamIndicesByName().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
       */
      public Builder putParamIndicesByName(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableParamIndicesByName().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; paramIndicesByName = 3;</code>
       */

      public Builder putAllParamIndicesByName(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableParamIndicesByName().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> paramTypesByName_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetParamTypesByName() {
        if (paramTypesByName_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParamTypesByNameDefaultEntryHolder.defaultEntry);
        }
        return paramTypesByName_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableParamTypesByName() {
        onChanged();;
        if (paramTypesByName_ == null) {
          paramTypesByName_ = com.google.protobuf.MapField.newMapField(
              ParamTypesByNameDefaultEntryHolder.defaultEntry);
        }
        if (!paramTypesByName_.isMutable()) {
          paramTypesByName_ = paramTypesByName_.copy();
        }
        return paramTypesByName_;
      }

      public int getParamTypesByNameCount() {
        return internalGetParamTypesByName().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
       */

      public boolean containsParamTypesByName(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetParamTypesByName().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParamTypesByNameMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getParamTypesByName() {
        return getParamTypesByNameMap();
      }
      /**
       * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getParamTypesByNameMap() {
        return internalGetParamTypesByName().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
       */

      public java.lang.String getParamTypesByNameOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetParamTypesByName().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
       */

      public java.lang.String getParamTypesByNameOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetParamTypesByName().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParamTypesByName() {
        internalGetMutableParamTypesByName().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
       */

      public Builder removeParamTypesByName(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParamTypesByName().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableParamTypesByName() {
        return internalGetMutableParamTypesByName().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
       */
      public Builder putParamTypesByName(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParamTypesByName().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; paramTypesByName = 4;</code>
       */

      public Builder putAllParamTypesByName(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableParamTypesByName().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object partitionKey_ = "";
      /**
       * <code>string partitionKey = 5;</code>
       */
      public java.lang.String getPartitionKey() {
        java.lang.Object ref = partitionKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          partitionKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string partitionKey = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPartitionKeyBytes() {
        java.lang.Object ref = partitionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partitionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string partitionKey = 5;</code>
       */
      public Builder setPartitionKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partitionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string partitionKey = 5;</code>
       */
      public Builder clearPartitionKey() {
        
        partitionKey_ = getDefaultInstance().getPartitionKey();
        onChanged();
        return this;
      }
      /**
       * <code>string partitionKey = 5;</code>
       */
      public Builder setPartitionKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        partitionKey_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.FpDbEvent)
    }

    // @@protoc_insertion_point(class_scope:model.FpDbEvent)
    private static final com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent();
    }

    public static com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FpDbEvent>
        PARSER = new com.google.protobuf.AbstractParser<FpDbEvent>() {
      @java.lang.Override
      public FpDbEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FpDbEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FpDbEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FpDbEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kloudfuse.log4j2.model.proto.FpDbEventOuterClass.FpDbEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_FpDbEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_FpDbEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_FpDbEvent_ParamIndicesByNameEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_FpDbEvent_ParamIndicesByNameEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_FpDbEvent_ParamTypesByNameEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_FpDbEvent_ParamTypesByNameEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017FpDbEvent.proto\022\005model\"\316\002\n\tFpDbEvent\022\027" +
      "\n\017fingerprintHash\030\001 \001(\t\022\026\n\016fingerprintSt" +
      "r\030\002 \001(\t\022D\n\022paramIndicesByName\030\003 \003(\0132(.mo" +
      "del.FpDbEvent.ParamIndicesByNameEntry\022@\n" +
      "\020paramTypesByName\030\004 \003(\0132&.model.FpDbEven" +
      "t.ParamTypesByNameEntry\022\024\n\014partitionKey\030" +
      "\005 \001(\t\0329\n\027ParamIndicesByNameEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\0327\n\025ParamTypesBy" +
      "NameEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001B\"\n com.kloudfuse.log4j2.model.protob\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_FpDbEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_FpDbEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_FpDbEvent_descriptor,
        new java.lang.String[] { "FingerprintHash", "FingerprintStr", "ParamIndicesByName", "ParamTypesByName", "PartitionKey", });
    internal_static_model_FpDbEvent_ParamIndicesByNameEntry_descriptor =
      internal_static_model_FpDbEvent_descriptor.getNestedTypes().get(0);
    internal_static_model_FpDbEvent_ParamIndicesByNameEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_FpDbEvent_ParamIndicesByNameEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_model_FpDbEvent_ParamTypesByNameEntry_descriptor =
      internal_static_model_FpDbEvent_descriptor.getNestedTypes().get(1);
    internal_static_model_FpDbEvent_ParamTypesByNameEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_FpDbEvent_ParamTypesByNameEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
