// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeltDbEvent.proto

package com.kloudfuse.log4j2.model.proto;

public final class MeltDbEventOuterClass {
  private MeltDbEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MeltDbEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.MeltDbEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fingerprintHash = 1;</code>
     */
    java.lang.String getFingerprintHash();
    /**
     * <code>string fingerprintHash = 1;</code>
     */
    com.google.protobuf.ByteString
        getFingerprintHashBytes();

    /**
     * <code>repeated int64 longs = 2;</code>
     */
    java.util.List<java.lang.Long> getLongsList();
    /**
     * <code>repeated int64 longs = 2;</code>
     */
    int getLongsCount();
    /**
     * <code>repeated int64 longs = 2;</code>
     */
    long getLongs(int index);

    /**
     * <code>repeated double doubles = 3;</code>
     */
    java.util.List<java.lang.Double> getDoublesList();
    /**
     * <code>repeated double doubles = 3;</code>
     */
    int getDoublesCount();
    /**
     * <code>repeated double doubles = 3;</code>
     */
    double getDoubles(int index);

    /**
     * <code>repeated string strings = 4;</code>
     */
    java.util.List<java.lang.String>
        getStringsList();
    /**
     * <code>repeated string strings = 4;</code>
     */
    int getStringsCount();
    /**
     * <code>repeated string strings = 4;</code>
     */
    java.lang.String getStrings(int index);
    /**
     * <code>repeated string strings = 4;</code>
     */
    com.google.protobuf.ByteString
        getStringsBytes(int index);

    /**
     * <code>string fileName = 5;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 5;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>string kube_namespace = 6;</code>
     */
    java.lang.String getKubeNamespace();
    /**
     * <code>string kube_namespace = 6;</code>
     */
    com.google.protobuf.ByteString
        getKubeNamespaceBytes();

    /**
     * <code>string kube_container_name = 7;</code>
     */
    java.lang.String getKubeContainerName();
    /**
     * <code>string kube_container_name = 7;</code>
     */
    com.google.protobuf.ByteString
        getKubeContainerNameBytes();

    /**
     * <code>string kube_service = 8;</code>
     */
    java.lang.String getKubeService();
    /**
     * <code>string kube_service = 8;</code>
     */
    com.google.protobuf.ByteString
        getKubeServiceBytes();

    /**
     * <code>string kube_deployment = 9;</code>
     */
    java.lang.String getKubeDeployment();
    /**
     * <code>string kube_deployment = 9;</code>
     */
    com.google.protobuf.ByteString
        getKubeDeploymentBytes();

    /**
     * <code>string short_image = 10;</code>
     */
    java.lang.String getShortImage();
    /**
     * <code>string short_image = 10;</code>
     */
    com.google.protobuf.ByteString
        getShortImageBytes();

    /**
     * <code>string pod_phase = 11;</code>
     */
    java.lang.String getPodPhase();
    /**
     * <code>string pod_phase = 11;</code>
     */
    com.google.protobuf.ByteString
        getPodPhaseBytes();

    /**
     * <code>string kube_ownerref_name = 12;</code>
     */
    java.lang.String getKubeOwnerrefName();
    /**
     * <code>string kube_ownerref_name = 12;</code>
     */
    com.google.protobuf.ByteString
        getKubeOwnerrefNameBytes();

    /**
     * <code>string kube_replica_set = 13;</code>
     */
    java.lang.String getKubeReplicaSet();
    /**
     * <code>string kube_replica_set = 13;</code>
     */
    com.google.protobuf.ByteString
        getKubeReplicaSetBytes();

    /**
     * <code>string display_container_name = 14;</code>
     */
    java.lang.String getDisplayContainerName();
    /**
     * <code>string display_container_name = 14;</code>
     */
    com.google.protobuf.ByteString
        getDisplayContainerNameBytes();

    /**
     * <code>string container_id = 15;</code>
     */
    java.lang.String getContainerId();
    /**
     * <code>string container_id = 15;</code>
     */
    com.google.protobuf.ByteString
        getContainerIdBytes();

    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */
    int getTagsCount();
    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */
    boolean containsTags(
        java.lang.String key);
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTags();
    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTagsMap();
    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */

    java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */

    java.lang.String getTagsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code model.MeltDbEvent}
   */
  public  static final class MeltDbEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.MeltDbEvent)
      MeltDbEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MeltDbEvent.newBuilder() to construct.
    private MeltDbEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MeltDbEvent() {
      fingerprintHash_ = "";
      longs_ = emptyLongList();
      doubles_ = emptyDoubleList();
      strings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fileName_ = "";
      kubeNamespace_ = "";
      kubeContainerName_ = "";
      kubeService_ = "";
      kubeDeployment_ = "";
      shortImage_ = "";
      podPhase_ = "";
      kubeOwnerrefName_ = "";
      kubeReplicaSet_ = "";
      displayContainerName_ = "";
      containerId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MeltDbEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fingerprintHash_ = s;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                longs_ = newLongList();
                mutable_bitField0_ |= 0x00000002;
              }
              longs_.addLong(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                longs_ = newLongList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                longs_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 25: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                doubles_ = newDoubleList();
                mutable_bitField0_ |= 0x00000004;
              }
              doubles_.addDouble(input.readDouble());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                doubles_ = newDoubleList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                doubles_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                strings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              strings_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              kubeNamespace_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              kubeContainerName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              kubeService_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              kubeDeployment_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              shortImage_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              podPhase_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              kubeOwnerrefName_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              kubeReplicaSet_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              displayContainerName_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              containerId_ = s;
              break;
            }
            case 130: {
              if (!((mutable_bitField0_ & 0x00008000) != 0)) {
                tags_ = com.google.protobuf.MapField.newMapField(
                    TagsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00008000;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              tags__ = input.readMessage(
                  TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              tags_.getMutableMap().put(
                  tags__.getKey(), tags__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          longs_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          doubles_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          strings_ = strings_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.internal_static_model_MeltDbEvent_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 16:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.internal_static_model_MeltDbEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent.class, com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent.Builder.class);
    }

    private int bitField0_;
    public static final int FINGERPRINTHASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object fingerprintHash_;
    /**
     * <code>string fingerprintHash = 1;</code>
     */
    public java.lang.String getFingerprintHash() {
      java.lang.Object ref = fingerprintHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fingerprintHash_ = s;
        return s;
      }
    }
    /**
     * <code>string fingerprintHash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFingerprintHashBytes() {
      java.lang.Object ref = fingerprintHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fingerprintHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.LongList longs_;
    /**
     * <code>repeated int64 longs = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getLongsList() {
      return longs_;
    }
    /**
     * <code>repeated int64 longs = 2;</code>
     */
    public int getLongsCount() {
      return longs_.size();
    }
    /**
     * <code>repeated int64 longs = 2;</code>
     */
    public long getLongs(int index) {
      return longs_.getLong(index);
    }
    private int longsMemoizedSerializedSize = -1;

    public static final int DOUBLES_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.DoubleList doubles_;
    /**
     * <code>repeated double doubles = 3;</code>
     */
    public java.util.List<java.lang.Double>
        getDoublesList() {
      return doubles_;
    }
    /**
     * <code>repeated double doubles = 3;</code>
     */
    public int getDoublesCount() {
      return doubles_.size();
    }
    /**
     * <code>repeated double doubles = 3;</code>
     */
    public double getDoubles(int index) {
      return doubles_.getDouble(index);
    }
    private int doublesMemoizedSerializedSize = -1;

    public static final int STRINGS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList strings_;
    /**
     * <code>repeated string strings = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStringsList() {
      return strings_;
    }
    /**
     * <code>repeated string strings = 4;</code>
     */
    public int getStringsCount() {
      return strings_.size();
    }
    /**
     * <code>repeated string strings = 4;</code>
     */
    public java.lang.String getStrings(int index) {
      return strings_.get(index);
    }
    /**
     * <code>repeated string strings = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStringsBytes(int index) {
      return strings_.getByteString(index);
    }

    public static final int FILENAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 5;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KUBE_NAMESPACE_FIELD_NUMBER = 6;
    private volatile java.lang.Object kubeNamespace_;
    /**
     * <code>string kube_namespace = 6;</code>
     */
    public java.lang.String getKubeNamespace() {
      java.lang.Object ref = kubeNamespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kubeNamespace_ = s;
        return s;
      }
    }
    /**
     * <code>string kube_namespace = 6;</code>
     */
    public com.google.protobuf.ByteString
        getKubeNamespaceBytes() {
      java.lang.Object ref = kubeNamespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kubeNamespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KUBE_CONTAINER_NAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object kubeContainerName_;
    /**
     * <code>string kube_container_name = 7;</code>
     */
    public java.lang.String getKubeContainerName() {
      java.lang.Object ref = kubeContainerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kubeContainerName_ = s;
        return s;
      }
    }
    /**
     * <code>string kube_container_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getKubeContainerNameBytes() {
      java.lang.Object ref = kubeContainerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kubeContainerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KUBE_SERVICE_FIELD_NUMBER = 8;
    private volatile java.lang.Object kubeService_;
    /**
     * <code>string kube_service = 8;</code>
     */
    public java.lang.String getKubeService() {
      java.lang.Object ref = kubeService_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kubeService_ = s;
        return s;
      }
    }
    /**
     * <code>string kube_service = 8;</code>
     */
    public com.google.protobuf.ByteString
        getKubeServiceBytes() {
      java.lang.Object ref = kubeService_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kubeService_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KUBE_DEPLOYMENT_FIELD_NUMBER = 9;
    private volatile java.lang.Object kubeDeployment_;
    /**
     * <code>string kube_deployment = 9;</code>
     */
    public java.lang.String getKubeDeployment() {
      java.lang.Object ref = kubeDeployment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kubeDeployment_ = s;
        return s;
      }
    }
    /**
     * <code>string kube_deployment = 9;</code>
     */
    public com.google.protobuf.ByteString
        getKubeDeploymentBytes() {
      java.lang.Object ref = kubeDeployment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kubeDeployment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHORT_IMAGE_FIELD_NUMBER = 10;
    private volatile java.lang.Object shortImage_;
    /**
     * <code>string short_image = 10;</code>
     */
    public java.lang.String getShortImage() {
      java.lang.Object ref = shortImage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shortImage_ = s;
        return s;
      }
    }
    /**
     * <code>string short_image = 10;</code>
     */
    public com.google.protobuf.ByteString
        getShortImageBytes() {
      java.lang.Object ref = shortImage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POD_PHASE_FIELD_NUMBER = 11;
    private volatile java.lang.Object podPhase_;
    /**
     * <code>string pod_phase = 11;</code>
     */
    public java.lang.String getPodPhase() {
      java.lang.Object ref = podPhase_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        podPhase_ = s;
        return s;
      }
    }
    /**
     * <code>string pod_phase = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPodPhaseBytes() {
      java.lang.Object ref = podPhase_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        podPhase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KUBE_OWNERREF_NAME_FIELD_NUMBER = 12;
    private volatile java.lang.Object kubeOwnerrefName_;
    /**
     * <code>string kube_ownerref_name = 12;</code>
     */
    public java.lang.String getKubeOwnerrefName() {
      java.lang.Object ref = kubeOwnerrefName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kubeOwnerrefName_ = s;
        return s;
      }
    }
    /**
     * <code>string kube_ownerref_name = 12;</code>
     */
    public com.google.protobuf.ByteString
        getKubeOwnerrefNameBytes() {
      java.lang.Object ref = kubeOwnerrefName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kubeOwnerrefName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KUBE_REPLICA_SET_FIELD_NUMBER = 13;
    private volatile java.lang.Object kubeReplicaSet_;
    /**
     * <code>string kube_replica_set = 13;</code>
     */
    public java.lang.String getKubeReplicaSet() {
      java.lang.Object ref = kubeReplicaSet_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kubeReplicaSet_ = s;
        return s;
      }
    }
    /**
     * <code>string kube_replica_set = 13;</code>
     */
    public com.google.protobuf.ByteString
        getKubeReplicaSetBytes() {
      java.lang.Object ref = kubeReplicaSet_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kubeReplicaSet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPLAY_CONTAINER_NAME_FIELD_NUMBER = 14;
    private volatile java.lang.Object displayContainerName_;
    /**
     * <code>string display_container_name = 14;</code>
     */
    public java.lang.String getDisplayContainerName() {
      java.lang.Object ref = displayContainerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayContainerName_ = s;
        return s;
      }
    }
    /**
     * <code>string display_container_name = 14;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayContainerNameBytes() {
      java.lang.Object ref = displayContainerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayContainerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTAINER_ID_FIELD_NUMBER = 15;
    private volatile java.lang.Object containerId_;
    /**
     * <code>string container_id = 15;</code>
     */
    public java.lang.String getContainerId() {
      java.lang.Object ref = containerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        containerId_ = s;
        return s;
      }
    }
    /**
     * <code>string container_id = 15;</code>
     */
    public com.google.protobuf.ByteString
        getContainerIdBytes() {
      java.lang.Object ref = containerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        containerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGS_FIELD_NUMBER = 16;
    private static final class TagsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.internal_static_model_MeltDbEvent_TagsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }

    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */

    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */

    public java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 16;</code>
     */

    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getFingerprintHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fingerprintHash_);
      }
      if (getLongsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(longsMemoizedSerializedSize);
      }
      for (int i = 0; i < longs_.size(); i++) {
        output.writeInt64NoTag(longs_.getLong(i));
      }
      if (getDoublesList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(doublesMemoizedSerializedSize);
      }
      for (int i = 0; i < doubles_.size(); i++) {
        output.writeDoubleNoTag(doubles_.getDouble(i));
      }
      for (int i = 0; i < strings_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, strings_.getRaw(i));
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileName_);
      }
      if (!getKubeNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, kubeNamespace_);
      }
      if (!getKubeContainerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, kubeContainerName_);
      }
      if (!getKubeServiceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, kubeService_);
      }
      if (!getKubeDeploymentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, kubeDeployment_);
      }
      if (!getShortImageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, shortImage_);
      }
      if (!getPodPhaseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, podPhase_);
      }
      if (!getKubeOwnerrefNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, kubeOwnerrefName_);
      }
      if (!getKubeReplicaSetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, kubeReplicaSet_);
      }
      if (!getDisplayContainerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, displayContainerName_);
      }
      if (!getContainerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, containerId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTags(),
          TagsDefaultEntryHolder.defaultEntry,
          16);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFingerprintHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fingerprintHash_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < longs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(longs_.getLong(i));
        }
        size += dataSize;
        if (!getLongsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        longsMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDoublesList().size();
        size += dataSize;
        if (!getDoublesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        doublesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < strings_.size(); i++) {
          dataSize += computeStringSizeNoTag(strings_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStringsList().size();
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fileName_);
      }
      if (!getKubeNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, kubeNamespace_);
      }
      if (!getKubeContainerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, kubeContainerName_);
      }
      if (!getKubeServiceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, kubeService_);
      }
      if (!getKubeDeploymentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, kubeDeployment_);
      }
      if (!getShortImageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, shortImage_);
      }
      if (!getPodPhaseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, podPhase_);
      }
      if (!getKubeOwnerrefNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, kubeOwnerrefName_);
      }
      if (!getKubeReplicaSetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, kubeReplicaSet_);
      }
      if (!getDisplayContainerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, displayContainerName_);
      }
      if (!getContainerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, containerId_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTags().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(16, tags__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent)) {
        return super.equals(obj);
      }
      com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent other = (com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent) obj;

      if (!getFingerprintHash()
          .equals(other.getFingerprintHash())) return false;
      if (!getLongsList()
          .equals(other.getLongsList())) return false;
      if (!getDoublesList()
          .equals(other.getDoublesList())) return false;
      if (!getStringsList()
          .equals(other.getStringsList())) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getKubeNamespace()
          .equals(other.getKubeNamespace())) return false;
      if (!getKubeContainerName()
          .equals(other.getKubeContainerName())) return false;
      if (!getKubeService()
          .equals(other.getKubeService())) return false;
      if (!getKubeDeployment()
          .equals(other.getKubeDeployment())) return false;
      if (!getShortImage()
          .equals(other.getShortImage())) return false;
      if (!getPodPhase()
          .equals(other.getPodPhase())) return false;
      if (!getKubeOwnerrefName()
          .equals(other.getKubeOwnerrefName())) return false;
      if (!getKubeReplicaSet()
          .equals(other.getKubeReplicaSet())) return false;
      if (!getDisplayContainerName()
          .equals(other.getDisplayContainerName())) return false;
      if (!getContainerId()
          .equals(other.getContainerId())) return false;
      if (!internalGetTags().equals(
          other.internalGetTags())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FINGERPRINTHASH_FIELD_NUMBER;
      hash = (53 * hash) + getFingerprintHash().hashCode();
      if (getLongsCount() > 0) {
        hash = (37 * hash) + LONGS_FIELD_NUMBER;
        hash = (53 * hash) + getLongsList().hashCode();
      }
      if (getDoublesCount() > 0) {
        hash = (37 * hash) + DOUBLES_FIELD_NUMBER;
        hash = (53 * hash) + getDoublesList().hashCode();
      }
      if (getStringsCount() > 0) {
        hash = (37 * hash) + STRINGS_FIELD_NUMBER;
        hash = (53 * hash) + getStringsList().hashCode();
      }
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + KUBE_NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getKubeNamespace().hashCode();
      hash = (37 * hash) + KUBE_CONTAINER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getKubeContainerName().hashCode();
      hash = (37 * hash) + KUBE_SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getKubeService().hashCode();
      hash = (37 * hash) + KUBE_DEPLOYMENT_FIELD_NUMBER;
      hash = (53 * hash) + getKubeDeployment().hashCode();
      hash = (37 * hash) + SHORT_IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getShortImage().hashCode();
      hash = (37 * hash) + POD_PHASE_FIELD_NUMBER;
      hash = (53 * hash) + getPodPhase().hashCode();
      hash = (37 * hash) + KUBE_OWNERREF_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getKubeOwnerrefName().hashCode();
      hash = (37 * hash) + KUBE_REPLICA_SET_FIELD_NUMBER;
      hash = (53 * hash) + getKubeReplicaSet().hashCode();
      hash = (37 * hash) + DISPLAY_CONTAINER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDisplayContainerName().hashCode();
      hash = (37 * hash) + CONTAINER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getContainerId().hashCode();
      if (!internalGetTags().getMap().isEmpty()) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTags().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.MeltDbEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.MeltDbEvent)
        com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.internal_static_model_MeltDbEvent_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 16:
            return internalGetTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 16:
            return internalGetMutableTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.internal_static_model_MeltDbEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent.class, com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent.Builder.class);
      }

      // Construct using com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fingerprintHash_ = "";

        longs_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000002);
        doubles_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000004);
        strings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        fileName_ = "";

        kubeNamespace_ = "";

        kubeContainerName_ = "";

        kubeService_ = "";

        kubeDeployment_ = "";

        shortImage_ = "";

        podPhase_ = "";

        kubeOwnerrefName_ = "";

        kubeReplicaSet_ = "";

        displayContainerName_ = "";

        containerId_ = "";

        internalGetMutableTags().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.internal_static_model_MeltDbEvent_descriptor;
      }

      @java.lang.Override
      public com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent getDefaultInstanceForType() {
        return com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent build() {
        com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent buildPartial() {
        com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent result = new com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.fingerprintHash_ = fingerprintHash_;
        if (((bitField0_ & 0x00000002) != 0)) {
          longs_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.longs_ = longs_;
        if (((bitField0_ & 0x00000004) != 0)) {
          doubles_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.doubles_ = doubles_;
        if (((bitField0_ & 0x00000008) != 0)) {
          strings_ = strings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.strings_ = strings_;
        result.fileName_ = fileName_;
        result.kubeNamespace_ = kubeNamespace_;
        result.kubeContainerName_ = kubeContainerName_;
        result.kubeService_ = kubeService_;
        result.kubeDeployment_ = kubeDeployment_;
        result.shortImage_ = shortImage_;
        result.podPhase_ = podPhase_;
        result.kubeOwnerrefName_ = kubeOwnerrefName_;
        result.kubeReplicaSet_ = kubeReplicaSet_;
        result.displayContainerName_ = displayContainerName_;
        result.containerId_ = containerId_;
        result.tags_ = internalGetTags();
        result.tags_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent) {
          return mergeFrom((com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent other) {
        if (other == com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent.getDefaultInstance()) return this;
        if (!other.getFingerprintHash().isEmpty()) {
          fingerprintHash_ = other.fingerprintHash_;
          onChanged();
        }
        if (!other.longs_.isEmpty()) {
          if (longs_.isEmpty()) {
            longs_ = other.longs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLongsIsMutable();
            longs_.addAll(other.longs_);
          }
          onChanged();
        }
        if (!other.doubles_.isEmpty()) {
          if (doubles_.isEmpty()) {
            doubles_ = other.doubles_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDoublesIsMutable();
            doubles_.addAll(other.doubles_);
          }
          onChanged();
        }
        if (!other.strings_.isEmpty()) {
          if (strings_.isEmpty()) {
            strings_ = other.strings_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureStringsIsMutable();
            strings_.addAll(other.strings_);
          }
          onChanged();
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (!other.getKubeNamespace().isEmpty()) {
          kubeNamespace_ = other.kubeNamespace_;
          onChanged();
        }
        if (!other.getKubeContainerName().isEmpty()) {
          kubeContainerName_ = other.kubeContainerName_;
          onChanged();
        }
        if (!other.getKubeService().isEmpty()) {
          kubeService_ = other.kubeService_;
          onChanged();
        }
        if (!other.getKubeDeployment().isEmpty()) {
          kubeDeployment_ = other.kubeDeployment_;
          onChanged();
        }
        if (!other.getShortImage().isEmpty()) {
          shortImage_ = other.shortImage_;
          onChanged();
        }
        if (!other.getPodPhase().isEmpty()) {
          podPhase_ = other.podPhase_;
          onChanged();
        }
        if (!other.getKubeOwnerrefName().isEmpty()) {
          kubeOwnerrefName_ = other.kubeOwnerrefName_;
          onChanged();
        }
        if (!other.getKubeReplicaSet().isEmpty()) {
          kubeReplicaSet_ = other.kubeReplicaSet_;
          onChanged();
        }
        if (!other.getDisplayContainerName().isEmpty()) {
          displayContainerName_ = other.displayContainerName_;
          onChanged();
        }
        if (!other.getContainerId().isEmpty()) {
          containerId_ = other.containerId_;
          onChanged();
        }
        internalGetMutableTags().mergeFrom(
            other.internalGetTags());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fingerprintHash_ = "";
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public java.lang.String getFingerprintHash() {
        java.lang.Object ref = fingerprintHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fingerprintHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFingerprintHashBytes() {
        java.lang.Object ref = fingerprintHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fingerprintHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public Builder setFingerprintHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fingerprintHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public Builder clearFingerprintHash() {
        
        fingerprintHash_ = getDefaultInstance().getFingerprintHash();
        onChanged();
        return this;
      }
      /**
       * <code>string fingerprintHash = 1;</code>
       */
      public Builder setFingerprintHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fingerprintHash_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList longs_ = emptyLongList();
      private void ensureLongsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          longs_ = mutableCopy(longs_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int64 longs = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getLongsList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(longs_) : longs_;
      }
      /**
       * <code>repeated int64 longs = 2;</code>
       */
      public int getLongsCount() {
        return longs_.size();
      }
      /**
       * <code>repeated int64 longs = 2;</code>
       */
      public long getLongs(int index) {
        return longs_.getLong(index);
      }
      /**
       * <code>repeated int64 longs = 2;</code>
       */
      public Builder setLongs(
          int index, long value) {
        ensureLongsIsMutable();
        longs_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 longs = 2;</code>
       */
      public Builder addLongs(long value) {
        ensureLongsIsMutable();
        longs_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 longs = 2;</code>
       */
      public Builder addAllLongs(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureLongsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, longs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 longs = 2;</code>
       */
      public Builder clearLongs() {
        longs_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList doubles_ = emptyDoubleList();
      private void ensureDoublesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          doubles_ = mutableCopy(doubles_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated double doubles = 3;</code>
       */
      public java.util.List<java.lang.Double>
          getDoublesList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(doubles_) : doubles_;
      }
      /**
       * <code>repeated double doubles = 3;</code>
       */
      public int getDoublesCount() {
        return doubles_.size();
      }
      /**
       * <code>repeated double doubles = 3;</code>
       */
      public double getDoubles(int index) {
        return doubles_.getDouble(index);
      }
      /**
       * <code>repeated double doubles = 3;</code>
       */
      public Builder setDoubles(
          int index, double value) {
        ensureDoublesIsMutable();
        doubles_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double doubles = 3;</code>
       */
      public Builder addDoubles(double value) {
        ensureDoublesIsMutable();
        doubles_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double doubles = 3;</code>
       */
      public Builder addAllDoubles(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDoublesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, doubles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double doubles = 3;</code>
       */
      public Builder clearDoubles() {
        doubles_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList strings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          strings_ = new com.google.protobuf.LazyStringArrayList(strings_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStringsList() {
        return strings_.getUnmodifiableView();
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public int getStringsCount() {
        return strings_.size();
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public java.lang.String getStrings(int index) {
        return strings_.get(index);
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStringsBytes(int index) {
        return strings_.getByteString(index);
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder setStrings(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringsIsMutable();
        strings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder addStrings(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringsIsMutable();
        strings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder addAllStrings(
          java.lang.Iterable<java.lang.String> values) {
        ensureStringsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, strings_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder clearStrings() {
        strings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder addStringsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureStringsIsMutable();
        strings_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 5;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 5;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 5;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 5;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object kubeNamespace_ = "";
      /**
       * <code>string kube_namespace = 6;</code>
       */
      public java.lang.String getKubeNamespace() {
        java.lang.Object ref = kubeNamespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kubeNamespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kube_namespace = 6;</code>
       */
      public com.google.protobuf.ByteString
          getKubeNamespaceBytes() {
        java.lang.Object ref = kubeNamespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kubeNamespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kube_namespace = 6;</code>
       */
      public Builder setKubeNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kubeNamespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string kube_namespace = 6;</code>
       */
      public Builder clearKubeNamespace() {
        
        kubeNamespace_ = getDefaultInstance().getKubeNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string kube_namespace = 6;</code>
       */
      public Builder setKubeNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kubeNamespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object kubeContainerName_ = "";
      /**
       * <code>string kube_container_name = 7;</code>
       */
      public java.lang.String getKubeContainerName() {
        java.lang.Object ref = kubeContainerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kubeContainerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kube_container_name = 7;</code>
       */
      public com.google.protobuf.ByteString
          getKubeContainerNameBytes() {
        java.lang.Object ref = kubeContainerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kubeContainerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kube_container_name = 7;</code>
       */
      public Builder setKubeContainerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kubeContainerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string kube_container_name = 7;</code>
       */
      public Builder clearKubeContainerName() {
        
        kubeContainerName_ = getDefaultInstance().getKubeContainerName();
        onChanged();
        return this;
      }
      /**
       * <code>string kube_container_name = 7;</code>
       */
      public Builder setKubeContainerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kubeContainerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object kubeService_ = "";
      /**
       * <code>string kube_service = 8;</code>
       */
      public java.lang.String getKubeService() {
        java.lang.Object ref = kubeService_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kubeService_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kube_service = 8;</code>
       */
      public com.google.protobuf.ByteString
          getKubeServiceBytes() {
        java.lang.Object ref = kubeService_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kubeService_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kube_service = 8;</code>
       */
      public Builder setKubeService(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kubeService_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string kube_service = 8;</code>
       */
      public Builder clearKubeService() {
        
        kubeService_ = getDefaultInstance().getKubeService();
        onChanged();
        return this;
      }
      /**
       * <code>string kube_service = 8;</code>
       */
      public Builder setKubeServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kubeService_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object kubeDeployment_ = "";
      /**
       * <code>string kube_deployment = 9;</code>
       */
      public java.lang.String getKubeDeployment() {
        java.lang.Object ref = kubeDeployment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kubeDeployment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kube_deployment = 9;</code>
       */
      public com.google.protobuf.ByteString
          getKubeDeploymentBytes() {
        java.lang.Object ref = kubeDeployment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kubeDeployment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kube_deployment = 9;</code>
       */
      public Builder setKubeDeployment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kubeDeployment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string kube_deployment = 9;</code>
       */
      public Builder clearKubeDeployment() {
        
        kubeDeployment_ = getDefaultInstance().getKubeDeployment();
        onChanged();
        return this;
      }
      /**
       * <code>string kube_deployment = 9;</code>
       */
      public Builder setKubeDeploymentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kubeDeployment_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shortImage_ = "";
      /**
       * <code>string short_image = 10;</code>
       */
      public java.lang.String getShortImage() {
        java.lang.Object ref = shortImage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shortImage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string short_image = 10;</code>
       */
      public com.google.protobuf.ByteString
          getShortImageBytes() {
        java.lang.Object ref = shortImage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shortImage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string short_image = 10;</code>
       */
      public Builder setShortImage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shortImage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string short_image = 10;</code>
       */
      public Builder clearShortImage() {
        
        shortImage_ = getDefaultInstance().getShortImage();
        onChanged();
        return this;
      }
      /**
       * <code>string short_image = 10;</code>
       */
      public Builder setShortImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shortImage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object podPhase_ = "";
      /**
       * <code>string pod_phase = 11;</code>
       */
      public java.lang.String getPodPhase() {
        java.lang.Object ref = podPhase_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          podPhase_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pod_phase = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPodPhaseBytes() {
        java.lang.Object ref = podPhase_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          podPhase_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pod_phase = 11;</code>
       */
      public Builder setPodPhase(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        podPhase_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pod_phase = 11;</code>
       */
      public Builder clearPodPhase() {
        
        podPhase_ = getDefaultInstance().getPodPhase();
        onChanged();
        return this;
      }
      /**
       * <code>string pod_phase = 11;</code>
       */
      public Builder setPodPhaseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        podPhase_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object kubeOwnerrefName_ = "";
      /**
       * <code>string kube_ownerref_name = 12;</code>
       */
      public java.lang.String getKubeOwnerrefName() {
        java.lang.Object ref = kubeOwnerrefName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kubeOwnerrefName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kube_ownerref_name = 12;</code>
       */
      public com.google.protobuf.ByteString
          getKubeOwnerrefNameBytes() {
        java.lang.Object ref = kubeOwnerrefName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kubeOwnerrefName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kube_ownerref_name = 12;</code>
       */
      public Builder setKubeOwnerrefName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kubeOwnerrefName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string kube_ownerref_name = 12;</code>
       */
      public Builder clearKubeOwnerrefName() {
        
        kubeOwnerrefName_ = getDefaultInstance().getKubeOwnerrefName();
        onChanged();
        return this;
      }
      /**
       * <code>string kube_ownerref_name = 12;</code>
       */
      public Builder setKubeOwnerrefNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kubeOwnerrefName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object kubeReplicaSet_ = "";
      /**
       * <code>string kube_replica_set = 13;</code>
       */
      public java.lang.String getKubeReplicaSet() {
        java.lang.Object ref = kubeReplicaSet_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kubeReplicaSet_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kube_replica_set = 13;</code>
       */
      public com.google.protobuf.ByteString
          getKubeReplicaSetBytes() {
        java.lang.Object ref = kubeReplicaSet_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kubeReplicaSet_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kube_replica_set = 13;</code>
       */
      public Builder setKubeReplicaSet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kubeReplicaSet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string kube_replica_set = 13;</code>
       */
      public Builder clearKubeReplicaSet() {
        
        kubeReplicaSet_ = getDefaultInstance().getKubeReplicaSet();
        onChanged();
        return this;
      }
      /**
       * <code>string kube_replica_set = 13;</code>
       */
      public Builder setKubeReplicaSetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kubeReplicaSet_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object displayContainerName_ = "";
      /**
       * <code>string display_container_name = 14;</code>
       */
      public java.lang.String getDisplayContainerName() {
        java.lang.Object ref = displayContainerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          displayContainerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string display_container_name = 14;</code>
       */
      public com.google.protobuf.ByteString
          getDisplayContainerNameBytes() {
        java.lang.Object ref = displayContainerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displayContainerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string display_container_name = 14;</code>
       */
      public Builder setDisplayContainerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        displayContainerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string display_container_name = 14;</code>
       */
      public Builder clearDisplayContainerName() {
        
        displayContainerName_ = getDefaultInstance().getDisplayContainerName();
        onChanged();
        return this;
      }
      /**
       * <code>string display_container_name = 14;</code>
       */
      public Builder setDisplayContainerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        displayContainerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object containerId_ = "";
      /**
       * <code>string container_id = 15;</code>
       */
      public java.lang.String getContainerId() {
        java.lang.Object ref = containerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          containerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string container_id = 15;</code>
       */
      public com.google.protobuf.ByteString
          getContainerIdBytes() {
        java.lang.Object ref = containerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          containerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string container_id = 15;</code>
       */
      public Builder setContainerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        containerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string container_id = 15;</code>
       */
      public Builder clearContainerId() {
        
        containerId_ = getDefaultInstance().getContainerId();
        onChanged();
        return this;
      }
      /**
       * <code>string container_id = 15;</code>
       */
      public Builder setContainerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        containerId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> tags_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTags() {
        if (tags_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        return tags_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTags() {
        onChanged();;
        if (tags_ == null) {
          tags_ = com.google.protobuf.MapField.newMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        if (!tags_.isMutable()) {
          tags_ = tags_.copy();
        }
        return tags_;
      }

      public int getTagsCount() {
        return internalGetTags().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 16;</code>
       */

      public boolean containsTags(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTags().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTagsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTags() {
        return getTagsMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 16;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
        return internalGetTags().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 16;</code>
       */

      public java.lang.String getTagsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 16;</code>
       */

      public java.lang.String getTagsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTags() {
        internalGetMutableTags().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 16;</code>
       */

      public Builder removeTags(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTags().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTags() {
        return internalGetMutableTags().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 16;</code>
       */
      public Builder putTags(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTags().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 16;</code>
       */

      public Builder putAllTags(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableTags().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.MeltDbEvent)
    }

    // @@protoc_insertion_point(class_scope:model.MeltDbEvent)
    private static final com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent();
    }

    public static com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MeltDbEvent>
        PARSER = new com.google.protobuf.AbstractParser<MeltDbEvent>() {
      @java.lang.Override
      public MeltDbEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MeltDbEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MeltDbEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MeltDbEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kloudfuse.log4j2.model.proto.MeltDbEventOuterClass.MeltDbEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_MeltDbEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_MeltDbEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_MeltDbEvent_TagsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_MeltDbEvent_TagsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MeltDbEvent.proto\022\005model\"\272\003\n\013MeltDbEve" +
      "nt\022\027\n\017fingerprintHash\030\001 \001(\t\022\r\n\005longs\030\002 \003" +
      "(\003\022\017\n\007doubles\030\003 \003(\001\022\017\n\007strings\030\004 \003(\t\022\020\n\010" +
      "fileName\030\005 \001(\t\022\026\n\016kube_namespace\030\006 \001(\t\022\033" +
      "\n\023kube_container_name\030\007 \001(\t\022\024\n\014kube_serv" +
      "ice\030\010 \001(\t\022\027\n\017kube_deployment\030\t \001(\t\022\023\n\013sh" +
      "ort_image\030\n \001(\t\022\021\n\tpod_phase\030\013 \001(\t\022\032\n\022ku" +
      "be_ownerref_name\030\014 \001(\t\022\030\n\020kube_replica_s" +
      "et\030\r \001(\t\022\036\n\026display_container_name\030\016 \001(\t" +
      "\022\024\n\014container_id\030\017 \001(\t\022*\n\004tags\030\020 \003(\0132\034.m" +
      "odel.MeltDbEvent.TagsEntry\032+\n\tTagsEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\"\n com.k" +
      "loudfuse.log4j2.model.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_MeltDbEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_MeltDbEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_MeltDbEvent_descriptor,
        new java.lang.String[] { "FingerprintHash", "Longs", "Doubles", "Strings", "FileName", "KubeNamespace", "KubeContainerName", "KubeService", "KubeDeployment", "ShortImage", "PodPhase", "KubeOwnerrefName", "KubeReplicaSet", "DisplayContainerName", "ContainerId", "Tags", });
    internal_static_model_MeltDbEvent_TagsEntry_descriptor =
      internal_static_model_MeltDbEvent_descriptor.getNestedTypes().get(0);
    internal_static_model_MeltDbEvent_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_MeltDbEvent_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
